<?php

namespace App\Livewire\Store;

use App\Services\StoreService;
use App\Dtos\Store\CreateStoreDto;
use App\Repositories\StoreRepository;
use App\Livewire\Forms\StoreForm;
use App\Models\Organization;
use Livewire\Component;
use Livewire\WithPagination;

class StoreIndex extends Component
{
    use WithPagination;

    public StoreForm $form;

    public $search = '';
    public $perPage = 10;
    public $sortField = 'name';
    public $sortDirection = 'asc';

    // Modal state
    public $selectedStoreId = null;
    public $isEditMode = false;

    // Delete modal state
    public $storeToDelete = null;

    protected $queryString = [
        'search' => ['except' => ''],
        'sortField' => ['except' => 'name'],
        'sortDirection' => ['except' => 'asc'],
    ];

    public function openCreateModal(StoreRepository $repository): void
    {
        $this->form->reset();
        $this->selectedStoreId = null;
        $this->isEditMode = false;
        $organizationId = session('current_organization_id') ?? auth()->user()->default_organization_id;
        $this->form->code = $repository->generateNextCode($organizationId);
        $this->form->organization_id = $organizationId;
    }

    public function openEditModal(StoreRepository $repository, $storeId): void
    {
        try {
            $store = $repository->find($storeId);
            if (!$store) {
                $this->dispatch('show-toast', message: 'Magasin introuvable.', type: 'error');
                return;
            }
            $this->form->reset();
            $this->selectedStoreId = $store->id;
            $this->isEditMode = true;
            $this->form->setStore($store);
            $this->dispatch('open-edit-modal');
        } catch (\Exception $e) {
            $this->dispatch('show-toast', message: 'Une erreur est survenue.', type: 'error');
        }
    }

    public function save(StoreService $service): void
    {
        $this->form->validate();

        try {
            $data = $this->form->toArray();

            if ($this->isEditMode) {
                // Update
                $service->updateStore($this->selectedStoreId, $data);
                $this->dispatch('show-toast', message: 'Magasin mis à jour avec succès !', type: 'success');
            } else {
                // Create - code will be auto-generated by the service
                $organizationId = session('current_organization_id') ?? auth()->user()->default_organization_id;
                $dto = new CreateStoreDto(
                    name: $data['name'],
                    code: null, // Auto-generated
                    address: $data['address'] ?? null,
                    phone: $data['phone'] ?? null,
                    email: $data['email'] ?? null,
                    managerId: null,
                    organizationId: $organizationId,
                    isActive: $data['is_active'] ?? true,
                    isMain: $data['is_main'] ?? false,
                    settings: null
                );
                $service->createStore($dto->toArray());
                $this->dispatch('show-toast', message: 'Magasin créé avec succès !', type: 'success');
            }

            $this->dispatch('close-store-modal');
            $this->form->reset();
            $this->selectedStoreId = null;
            $this->isEditMode = false;

        } catch (\Exception $e) {
            $this->dispatch('show-toast', message: 'Erreur : ' . $e->getMessage(), type: 'error');
        }
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            $this->sortField = $field;
            $this->sortDirection = 'asc';
        }

        $this->resetPage();
    }

    public function confirmDelete($storeId)
    {
        $this->storeToDelete = $storeId;
    }

    public function deleteStore(StoreService $service, $storeId = null)
    {
        $idToDelete = $storeId ?? $this->storeToDelete;

        if (!$idToDelete) {
            return;
        }

        try {
            $service->deleteStore($idToDelete);

            $this->storeToDelete = null;
            $this->dispatch('show-toast', message: 'Magasin supprimé avec succès !', type: 'success');
            $this->resetPage();

        } catch (\Exception $e) {
            $this->dispatch('show-toast', message: 'Erreur : ' . $e->getMessage(), type: 'error');
        }
    }

    public function toggleStatus($storeId, StoreService $service)
    {
        try {
            $store = $service->getStoreById($storeId);
            $newStatus = !$store->is_active;

            $service->updateStore($storeId, [
                'is_active' => $newStatus,
            ]);

            $message = $newStatus ? 'Magasin activé avec succès !' : 'Magasin désactivé avec succès !';
            $this->dispatch('show-toast', message: $message, type: 'success');

        } catch (\Exception $e) {
            $this->dispatch('show-toast', message: 'Erreur : ' . $e->getMessage(), type: 'error');
        }
    }

    public function render(StoreService $service)
    {
        $stores = $service->getAllStores(
            search: $this->search,
            sortBy: $this->sortField,
            sortDirection: $this->sortDirection,
            perPage: $this->perPage
        );

        // Get store statistics
        $statistics = [];
        foreach ($stores as $store) {
            $statistics[$store->id] = $service->getStoreStatistics($store->id);
        }

        // Get organization for quota check
        $organizationId = session('current_organization_id') ?? auth()->user()->default_organization_id;
        $organization = Organization::find($organizationId);
        $canCreateStore = $organization ? $organization->canAddStore() && auth()->user()->can('createStore', $organization) : false;
        $storesUsage = $organization ? $organization->getStoresUsage() : null;

        return view('livewire.store.index', [
            'stores' => $stores,
            'statistics' => $statistics,
            'organization' => $organization,
            'canCreateStore' => $canCreateStore,
            'storesUsage' => $storesUsage,
        ]);
    }
}
